<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="aspire1437" name="com.temenos.testscripts.ManagePayees" tests="10" failures="2" timestamp="20 Nov 2017 18:50:48 GMT" time="940.102" errors="0">
  <testcase name="TC_TCIB_ManagePayees_009" time="26.265" classname="com.temenos.testscripts.ManagePayees"/>
  <testcase name="TC_TCIB_ManagePayees_005" time="190.081" classname="com.temenos.testscripts.ManagePayees"/>
  <testcase name="TC_TCIB_ManagePayees_008" time="76.543" classname="com.temenos.testscripts.ManagePayees">
    <failure type="java.lang.AssertionError" message="Actual : Test Failed. Check the steps above in red color.">
      <![CDATA[java.lang.AssertionError: Actual : Test Failed. Check the steps above in red color.
	at org.testng.Assert.fail(Assert.java:94)
	at com.temenos.support.Log.fail(Log.java:554)
	at com.temenos.support.Log.testCaseResult(Log.java:250)
	at com.temenos.testscripts.ManagePayees.TC_TCIB_ManagePayees_008(ManagePayees.java:510)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC_TCIB_ManagePayees_008 -->
  <testcase name="TC_TCIB_ManagePayees_001" time="137.573" classname="com.temenos.testscripts.ManagePayees"/>
  <testcase name="TC_TCIB_ManagePayees_010" time="34.789" classname="com.temenos.testscripts.ManagePayees"/>
  <testcase name="TC_TCIB_ManagePayees_004" time="63.643" classname="com.temenos.testscripts.ManagePayees"/>
  <testcase name="TC_TCIB_ManagePayees_002" time="87.604" classname="com.temenos.testscripts.ManagePayees"/>
  <testcase name="TC_TCIB_ManagePayees_007" time="198.503" classname="com.temenos.testscripts.ManagePayees"/>
  <testcase name="TC_TCIB_ManagePayees_003" time="71.285" classname="com.temenos.testscripts.ManagePayees">
    <failure type="java.lang.AssertionError" message="Actual : Test Failed. Check the steps above in red color.">
      <![CDATA[java.lang.AssertionError: Actual : Test Failed. Check the steps above in red color.
	at org.testng.Assert.fail(Assert.java:94)
	at com.temenos.support.Log.fail(Log.java:554)
	at com.temenos.support.Log.testCaseResult(Log.java:250)
	at com.temenos.testscripts.ManagePayees.TC_TCIB_ManagePayees_003(ManagePayees.java:222)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TC_TCIB_ManagePayees_003 -->
  <testcase name="TC_TCIB_ManagePayees_006" time="53.816" classname="com.temenos.testscripts.ManagePayees"/>
</testsuite> <!-- com.temenos.testscripts.ManagePayees -->
